#!/usr/bin/env python3
"""Здоровье кода: код не разрастается и не копируется — против базы, храповиком.

Развёрнут плагином studio (/studio/setup). Только стандартная библиотека; ничего не
ставит, продукт и движок не запускает. Зовут executor и reviewer
(--changed, --only), /studio/start, /studio/done (--tighten), /studio/board (--summary), /studio/idea
(--only), /studio/retro, /studio/setup.

    python -X utf8 tools/code_check.py [--changed [<хеш>] | --summary | --limits |
        --baseline [--add-new-metrics] | --tighten] [--only [<текст>]] [--root <папка>]
        [--baseline-file <путь>]

Файлы git и новые неотслеживаемые: .gd .cs .js .mjs .ts .tsx .py — всё;
шейдеры — повторы и наборы чисел; .tscn .tres .godot .html .json .cfg, а также
сжатое (*.min.*, средняя строка длиннее 300 знаков) и сгенерированное
(«auto-generated», «@generated», «code generated», «generated by <файл>.<расш>»,
«generated» с «do not edit» в комментарии в начале) — только имена, числом в
шапке (новый такой файл --changed называет заметкой); файл из базы меряется
всегда. Мимо: addons/, vendor/, node_modules/, скрытые папки, docs/, dist/ и
build/ в корне, шаблонные tools/, `exclude` базы и чужие неотслеживаемые
черновики _scratch*. Строки — значимые: без пустых и комментариев.

Без флагов — весь проект против базы tools/code_baseline.json; --changed —
только новое с <хеш> (HEAD): строка, удалённая в другом месте того же diff, —
перенос; функция, перенесённая целиком или с правкой вызовов (то же имя, тело
совпадает хоть наполовину), хранит свою базу, одноимённая в том же файле — по
телу («#2» после новой выше); переименованный файл — тоже. Размер с --changed
судится ростом против <хеш>, перенесённое в счёт. Повтор без флагов — сверх
числа мест в базе; повтор из базы, задетый уборкой (перенос с правкой,
соседние куски сошлись), — заметка, в базу его вносит --tighten (и число мест
поднимает); новая копия — находка, пока её не уберут. Цикл по имени — по
объявлению в функции, в файле или у предков (extends); с --changed Н5 ещё и
итогом (тип отняла правка другого файла), Н7 — и вызовы имён, которые diff
удалил. Н5 и Н6 на старой строке, где правлены только числа, текст или имена
переноса, с --changed — заметка. --only — только строки с <текстом>, все, без
обрезки до 20; без текста — все строки. --baseline и --tighten меряют
закоммиченное (HEAD; коммитов нет — рабочую папку). Горячий файл — по пунктам
своей партии (номера в партиях свои), кроме уборок («для игрока без
изменений»), под нынешним именем.
Находки (код 1): Н1 файл и Н2 функция длиннее порога (из базы — рост сверх
допуска), Н3 повтор блока, Н4 одноимённый помощник с тем же телом, Н5
GDScript без типа (если движок не ловит сам), Н6 проверка лезет в закрытое,
Н7 вызов по имени, которого нет, Н8 ослаблены типы, Н9 служба [autoload] без
записи в «Архитектуре» (с --changed — заметка: запись вносит /studio/done из строки
исполнителя `CONCEPT, Службы`), Н10 база поднята. Заметки (код 0) — материал
для уборки; первыми — горячие и сильнее переросшие. --summary — строка для
/studio/board; --limits — пороги; --baseline — записать базу (файл есть — отказ;
--add-new-metrics — дописать новые метрики); --tighten — снизить базу.

Коды возврата: 0 — чисто (заметки не в счёт); 1 — находки; 2 — неверный
вызов, нет git, нет базы или она испорчена.
"""
import argparse
import datetime
import difflib
import fnmatch
import hashlib
import json
import os
import re
import subprocess
import sys
from collections import Counter, defaultdict

VERSION = 1
BASE = "tools/code_baseline.json"
LANGS = {".gd": "gd", ".py": "py", ".cs": "cs", ".js": "js", ".mjs": "js", ".ts": "js", ".tsx": "js",
         ".gdshader": "shader", ".gdshaderinc": "shader", ".glsl": "shader", ".hlsl": "shader"}
NAMES_ONLY = {".tscn", ".tres", ".godot", ".html", ".htm", ".json", ".cfg"}
SKIP_DIRS = {"addons", "vendor", "node_modules", ".godot"}
SKIP_TOP = {"docs", "dist", "build"}
GENERATED = re.compile(r"(?i)\bauto-?generated\b|@generated\b|\bcode generated\b|\bgenerated by\s+[\w-]+\.\w+\b"
                       r"|\bgenerated\b.*\bdo not edit\b|\bdo not edit\b.*\bgenerated\b")  # не «Terrain generated by noise»
COUNTERS = ("untyped", "private", "byname")
OWN_TOOLS = {"tools/" + name for name in ("code_check.py", "roadmap_check.py", "refs_check.py", "asset_check.py",
                                          "look_sheet.py", "order_api.py", "load_all.gd", "code_baseline.json")}
TEST_DIRS = {"tests", "test", "__tests__", "spec"}
SECTIONS = ("files", "functions", "repeats", "helpers", "untyped", "private", "byname")
LIMITS = {
    "file_lines": (1000, "файл, значимых строк — max-file-lines gdlint"), "func_growth": (10, "рост функции из базы"),
    "file_growth": (20, "рост файла из базы — строка реестра и мелкая правка, не новая система"),
    "func_lines": (100, "функция — выбор по замеру (ESLint max-lines-per-function — 50)"),
    "call_lines": (3, "строки вызова нового в файле или функции из базы без запаса — заметка, не находка"),
    "repeat_lines": (8, "повтор блока, строк — выбор (jscpd — 5)"), "helper_lines": (3, "тело одноимённого помощника"),
    "note_file_lines": (600, "заметка: файл — около половины порога"), "note_func_lines": (60, "заметка: функция"),
    "class_fields": (30, "заметка: полей класса — выбор"), "hot_edits": (10, "горячий файл: правок из них — треть"),
    "class_methods": (20, "заметка: открытых методов — max-public-methods gdlint"),
    "hot_window": (30, "горячий файл: последних пунктов (партия и номер, не коммиты), кроме уборок"),
    "comment_share": (35, "заметка: доля строк-комментариев, %"), "folder_files": (30, "заметка: файлов кода в папке"),
    "types_batch": (150, "уборка типов: меньше — одним пунктом, больше — по папкам, большая папка — по файлам")}
VIRTUALS = set("""_ready _process _physics_process _input _unhandled_input _unhandled_key_input _shortcut_input _init
_enter_tree _exit_tree _notification _draw _gui_input _get _set _get_property_list _validate_property
_property_can_revert _property_get_revert _to_string _run _initialize _finalize _static_init
_get_configuration_warnings _can_drop_data _drop_data _get_drag_data _make_custom_tooltip _has_point _get_minimum_size
_integrate_forces _generate_block _get_used_channels_mask _iter_init _iter_next _iter_get _enable_plugin
_disable_plugin _handles _edit _make_visible _get_plugin_name _post_import _import _mix _start _stop _log_error
_log_message""".split())
CTRL = set("""if for foreach while switch catch using lock fixed return new else do try finally checked unchecked
await yield when typeof sizeof nameof with get set init add remove throw case default in of delete void base this""".split())
HEAD = re.compile(r"\s*(?:@\w+(?:\(.*?\))?\s+)*(?:static\s+)?(?:(func)|(?:async\s+)?(def)|(class))\s+([^\W\d]\w*)")
GD_VAR = re.compile(r"\s*(?:@\w+(?:\(.*?\))?\s+)*(?:static\s+)?var\s+(\w+)\s*(:=|:|=)?")
CLASSY = re.compile(r"\b(class|struct|record|interface|enum|namespace)\s+([^\W\d]\w*)")
FLOAT = re.compile(r"(?<![\w.])(\d+\.\d*|\.\d+)[fFdDmM]?(?![\w.])")
IDENT = re.compile(r"[^\W\d]\w*")  # и кириллица: func шаг_1, class_name СтарыйФайл
PRIVATE_CALL = re.compile(r"\.(?:get|set|call|callv|call_deferred|has_method)\(\s*&?[\"']_")
BYNAME = re.compile(r"(?:\.(?:call|callv|call_deferred|has_method)\(\s*|Callable\([^,()]*,\s*)&?\"([A-Z]\w*)\"")
CALLABLE = re.compile(r"\bfunc\s+(\w+)|\bpublic\b[^;{}=()]*?\b(\w+)\s*(?:<[^<>()]*>)?\s*\(")  # цель вызова по имени
UPTREE = re.compile(r"get_parent\(\)\.get_parent\(\)|GetParent\(\)\.GetParent\(\)|get_node\(\"\.\./"
                    r"|GetNode(?:<[^>]*>)?\(\"\.\./|\$\"?\.\./")
QUEUE_REF = re.compile(r"ROADMAP[^\n]{0,40}Подробност|«Подробности»,\s*\d|\b[Пп]ункт\w*\s+\d+|\bItem\s+\d+\b")
PUBLIC_CS = re.compile(r"\bpublic\b(?![^;{}=()]*\b(?:override|abstract|class|struct|record|interface|enum|"
                       r"delegate|event|operator)\b)[^;{}=()]*?\b([A-Za-z]\w*)\s*(?:<[^<>()]*>)?\s*\(")
INT_LOOP = re.compile(r"^(?:range|int|mini|maxi|absi|len)\(|\.(?:size|get_child_count)\(\)$|randi_range\(|^\d+$"
                      r"|[-+*/%]\s*\d+$")  # цикл по числу: тип выводит движок
TYPED_RETURN = r"\bfunc\s+(\w+)\s*\([^)]*\)\s*->\s*(?!(?:Array|Dictionary|Variant)\b(?!\[))\w"
DECL_TYPED = re.compile(r"[ \t]*(?::[ \t]*(?!(?:Array|Dictionary|Variant)\b(?!\[))[A-Za-z]"  # «:=» — тип выведен,
                        r"|:=[ \t]*(?![\[{]|(?:Array|Dictionary)[ \t]*\()\S)")  # кроме [], {} и Array() без типа
TYPED_CALLS = set("""get_children find_children get_nodes_in_group get_overlapping_bodies get_overlapping_areas
get_colliding_bodies get_groups split rsplit get_files_at get_directories_at get_files get_directories get_signal_list
get_method_list get_property_list get_meta_list get_incoming_connections""".split())
IGNORE_TYPES = re.compile(r"@warning_ignore[^)]*(untyped_declaration|unsafe_\w+)")


def git(root, *args, check=False):
    """Вызов git в папке проекта; текст вывода или None при ошибке."""
    try:
        run = subprocess.run(["git", "-c", "core.quotepath=off", "-C", root] + list(args), capture_output=True, timeout=60)
    except (OSError, subprocess.TimeoutExpired):
        return None
    return None if run.returncode != 0 and check else run.stdout.decode("utf-8", "replace")


def norm(line):
    return " ".join(line.split())


def digest(text):
    return hashlib.sha1(text.encode("utf-8")).hexdigest()[:12]


def is_test(path):
    *folders, name = path.split("/")
    return bool(TEST_DIRS & set(folders)) or name.startswith("test_") or re.search(r"[._]test\.|\.spec\.", name)


def is_check(path):
    """Проверка, а не стенд, зонд или съёмка из папки проверок: их вызовы — настоящее использование."""
    return is_test(path) and not re.search(r"probe|stage|stand|look|capture|bake|measure|shot", os.path.basename(path))


class Source:
    """Один файл: строки без комментариев, значимые строки, функции и классы."""

    def __init__(self, path, raw, lang):
        self.path, self.raw, self.lang, self.funcs, self.classes = path, raw, lang, [], []
        scan(self)
        self.size = sum(self.sig)
        {"gd": scopes_indent, "py": scopes_indent, "cs": scopes_brace, "js": scopes_brace}.get(lang, lambda _: None)(self)
        seen = Counter()
        for func in sorted(self.funcs, key=lambda f: f["start"]):  # перегрузки C# — разные ключи базы
            seen[func["qual"]] += 1
            func["qual"] += f"#{seen[func['qual']]}" if seen[func["qual"]] > 1 else ""

    def body(self, start, end):
        return [norm(self.text[i]) for i in range(start, end + 1) if self.sig[i]]


def scan(src):
    """text — без комментариев, литералы на месте; code — литералы пусты; sig, note, depth, cont по строкам."""
    hashy = src.lang in ("gd", "py")
    special = re.compile(r"[\"'#]" if hashy else r"[\"'`/]")
    src.text, src.code, src.sig, src.note, src.depth, src.cont = [], [], [], [], [], []
    state, depth = None, 0
    for line in src.raw:
        src.depth.append(depth)
        src.cont.append(state is not None)
        commented = state == "/*" or (state is not None and state[2])
        if state is None and not special.search(line):
            text = code = line
            depth = max(0, depth + sum(line.count(c) for c in "([{") - sum(line.count(c) for c in ")]}"))
        else:
            text, code, state, depth, hit = scan_line(line, state, depth, hashy, src.lang == "js")
            commented = commented or hit
        src.text.append(text)
        src.code.append(code)
        src.sig.append(bool(text.strip()))
        src.note.append(not text.strip() and commented and bool(line.strip()))
    src.depth.append(depth)
    src.cont.append(state is not None)


def scan_line(line, state, depth, hashy, js):
    """Одна строка посимвольно: строки-литералы, комментарии, скобки.

    tail — последние значимые знаки кода: по ним «/» в JS — начало регулярного выражения, а не деление
    (без склейки всей строки на каждом знаке — длинная строка разбиралась бы квадратично).
    """
    text, code, i, n, hit, tail = [], [], 0, len(line), False, ""
    while i < n:
        if state == "/*":
            j = line.find("*/", i)
            i, state = (n, state) if j < 0 else (j + 2, None)
            continue
        if state:
            quote, esc, doc = state
            j = i
            while j < n and not line.startswith(quote, j):
                j += 2 if esc and line[j] == "\\" else 1
            if not doc:
                text.append(line[i:j])
            if j >= n:
                state = None if len(quote) == 1 and quote != "`" and esc else state
                break
            if not esc and quote == '"' and line.startswith('""', j):
                text.append('""') if not doc else None
                i = j + 2
                continue
            if not doc:
                text.append(quote)
                code.append(quote)
                tail += quote
            i, state = j + len(quote), None
            continue
        ch = line[i]
        if (hashy and ch == "#") or (not hashy and line.startswith("//", i)):
            hit = True
            break
        if not hashy and line.startswith("/*", i):
            state, hit, i = "/*", True, i + 2
            continue
        if ch in "\"'`":
            quote = ch * 3 if hashy and line.startswith(ch * 3, i) else ch
            esc = not (not hashy and ch == '"' and line[max(0, i - 2):i].count("@"))
            doc = hashy and len(quote) == 3 and depth == 0 and not tail
            hit = hit or doc
            if not doc:
                text.append(quote)
                code.append(quote)
                tail += quote
            state, i = (quote, esc, doc), i + len(quote)
            continue
        if js and ch == "/" and re.search(r"(?:^|[(,=:\[!&|?{};]|=>|(?<!\w)return)$", tail[-7:]):
            j = i + 1
            while j < n and line[j] != "/":
                j += 2 if line[j] == "\\" else 1
            text.append(line[i:j + 1])
            code.append("//")
            tail, i = tail + "//", j + 1
            continue
        depth = depth + 1 if ch in "([{" else max(0, depth - 1) if ch in ")]}" else depth
        text.append(ch)
        code.append(ch)
        tail += "" if ch.isspace() else ch
        i += 1
    return "".join(text), "".join(code), state, depth, hit


def logical(src):
    """Логические строки GDScript и Python: (первая, последняя, отступ, код одной строкой)."""
    result, start = [], None
    for i, code in enumerate(src.code):
        if start is None and not src.sig[i]:
            continue
        start = i if start is None else start
        if src.depth[i + 1] == 0 and not src.cont[i + 1] and not code.rstrip().endswith("\\"):
            raw = src.raw[start]
            indent = len(raw[:len(raw) - len(raw.lstrip())].expandtabs(4))
            result.append((start, i, indent, " ".join(c.strip() for c in src.code[start:i + 1])))
            start = None
    return result


def new_scope(kind, name, start, owner, header=""):
    return {"kind": kind, "name": name, "start": start, "end": start, "owner": owner, "header": header,
            "fields": set(), "methods": 0, "decl": [start]}


def qual(scope):
    """Имя с именами владельцев до безымянного: Outer.Inner.run."""
    outer = qual(scope["owner"]) if scope and scope["name"] else ""
    return (outer + "." if outer else "") + scope["name"] if scope and scope["name"] else ""


def close(src, scope):
    if scope["kind"] == "func":
        body = src.body(scope["start"] + 1, scope["end"]) or src.body(scope["start"], scope["start"])
        size = sum(src.sig[scope["start"]:scope["end"] + 1])
        public = not scope["name"].startswith(("_", "#")) and (src.lang != "cs" or "public" in scope["header"])
        src.funcs.append({"name": scope["name"], "qual": qual(scope), "start": scope["start"],
                          "end": scope["end"], "size": size, "body": len(body), "public": public, "lines": body,
                          "print": digest(scope["name"] + "\n" + "\n".join(body))})
    elif scope["kind"] == "class":
        if src.lang in ("py", "js"):
            rx = r"\bself\.(\w+)\s*(?::[^=]*)?=(?!=)" if src.lang == "py" else r"\bthis\.(#?\w+)\s*=(?!=)"
            for i in range(scope["start"], scope["end"] + 1):
                scope["fields"].update(re.findall(rx, src.code[i]))
        src.classes.append({"name": scope["name"] or os.path.basename(src.path), "start": scope["start"],
                            "end": scope["end"], "fields": len(scope["fields"]), "methods": scope["methods"],
                            "decl": scope["decl"]})


def scopes_indent(src):
    """Функции и классы GDScript и Python по отступам."""
    top = dict(new_scope("class" if src.lang == "gd" else "module", "", 0, None), end=max(0, len(src.raw) - 1))
    stack = []
    for start, end, indent, code in logical(src):
        while stack and indent <= stack[-1][0]:
            close(src, stack.pop()[1])
        for _, scope in stack:
            scope["end"] = end
        owner = stack[-1][1] if stack else top
        head = HEAD.match(code)
        if head:
            kind = "class" if head.group(3) else "func"
            scope = new_scope(kind, head.group(4), start, owner)
            stack.append((indent, scope))
            if kind == "func" and owner["kind"] == "class":
                owner["decl"].append(start)
                owner["methods"] += not head.group(4).startswith("_")
        elif owner["kind"] == "class" and (GD_VAR.match(code) if src.lang == "gd" else re.match(r"\w+\s*[:=]", code)):
            owner["fields"].add(start)
            owner["decl"].append(start)
    while stack:
        close(src, stack.pop()[1])
    if src.lang == "gd":
        close(src, top)


def func_name(header):
    """Имя функции по заголовку перед «{» (C#, JS, TS); None — не объявление функции."""
    h = header.strip()
    if h.endswith("=>"):
        arrow = re.search(r"((?:[^\W\d]|\$)[\w$]*)\s*[:=]\s*(?:async\s*)?(?:\([^()]*\)|(?:[^\W\d]|\$)[\w$]*)\s*"
                          r"(?::[^=]*)?=>$", h)
        return arrow.group(1) if arrow else None
    h = re.sub(r"\s*:\s*(?:base|this)\s*\(.*\)$", "", h)
    h = re.sub(r"\)\s*(?::\s*[\w<>\[\]|.,?\s]+|where\s.*)$", ")", h)
    if not h.endswith(")"):
        return None
    depth, k = 0, len(h) - 1
    while k >= 0:
        depth += {")": 1, "(": -1}.get(h[k], 0)
        if depth == 0:
            break
        k -= 1
    before = re.sub(r"\s*<[^<>]*>$", "", h[:max(k, 0)].rstrip())
    found = re.search(r"((?:[^\W\d]|\$)[\w$]*)$", before)
    if k < 0 or not found:
        return None
    name, prev = found.group(1), before[:found.start()].rstrip()
    if name == "function":
        named = re.search(r"((?:[^\W\d]|\$)[\w$]*)\s*[:=]\s*(?:async\s+)?$", prev)
        return named.group(1) if named else None
    if name in CTRL or re.search(r"(?:\bnew|[.=(,!&|?])$", prev):
        return None
    return name


def scopes_brace(src):
    """Функции и классы C#, JS, TS по фигурным скобкам."""
    stack, head, head_line, paren, lit = [], [], None, 0, 0
    for ln, code in enumerate(src.code):
        if src.lang == "cs" and code.lstrip().startswith("#"):
            continue
        for part in re.split(r"([{};])", code) + [" "]:
            header = "".join(head).strip()
            # внутри скобок заголовка «{…}» и «;» — литерал или for(;;), кроме тела «=> {» и «) {»
            inner = paren > 0 and not (part == "{" and header.endswith(("=>", ")"))) or part == "}" and lit > 0
            if part not in ("{", "}", ";") or inner:
                head_line = ln if head_line is None and part.strip() else head_line
                head.append(part)
                paren = max(0, paren + part.count("(") - part.count(")"))
                lit += (part == "{") - (part == "}") if inner else 0
                continue
            start, owner = ln if head_line is None else head_line, stack[-1] if stack else None
            if part == "{":
                stack.append(brace_scope(header, start, owner, src.lang))
                stack[-1]["outer"], paren, lit = (paren, lit), 0, 0
            elif part == "}" and stack:
                scope = stack.pop()
                scope["end"], (paren, lit) = ln, scope["outer"]
                close(src, scope)
            elif part == ";" and owner and owner["kind"] == "class" and header:
                owner["decl"].append(start)
                if re.match(r"[^=(]*\w\s*(?:<[^>]*>)?\s*\(", header):
                    owner["methods"] += src.lang == "cs" and "public" in header.split("(")[0]
                elif not re.search(r"\b(?:const|static)\b", header):
                    owner["fields"].add(start)
            head, head_line = [], None


def brace_scope(header, start, owner, lang):
    classy = CLASSY.search(header)
    if classy and classy.group(1) != "enum" and "(" not in header[:classy.start()]:
        return new_scope("class" if classy.group(1) != "namespace" else "ns", classy.group(2)
                         if classy.group(1) != "namespace" else "", start, owner, header)
    name = func_name(header)
    in_class = owner is not None and owner["kind"] == "class"
    if name:
        if in_class:
            owner["decl"].append(start)
            owner["methods"] += not name.startswith(("_", "#")) and (lang != "cs" or "public" in header)
        return new_scope("func", name, start, owner, header)
    if in_class and header and "(" not in header and "=" not in header:
        owner["fields"].add(start)
        owner["decl"].append(start)
    return new_scope("block", "", start, owner, header)


def split_lines(text):
    lines = text.lstrip("\ufeff").replace("\r\n", "\n").split("\n")
    return lines[:-1] if lines and lines[-1] == "" else lines


def read_lines(path):
    try:
        with open(path, encoding="utf-8-sig", errors="replace") as handle:
            return split_lines(handle.read()) if os.path.getsize(path) <= 2_000_000 else None
    except OSError:
        return None


def generated(path, raw):
    """Сжатое или сгенерированное — только имена: *.min.*, метка в комментарии в начале, средняя строка > 300;
    причина или пусто. Одна длинная строка (картинка base64, список проверок) файл из замера не выводит.
    """
    long = [len(line) for line in raw if line.strip()]
    return "*.min.*" if ".min." in path.lower() else "средняя строка длиннее 300" if long and sum(
        long) / len(long) > 300 else next((f"метка «{line.strip()[:60]}»" for line in raw[:5] if GENERATED.search(
            line) and re.match(r"\s*(?:#|//|/?\*|<!--|;)", line)), "")


class Model:
    """Все файлы проекта: разобранный код и счёт имён по всему тексту.

    committed — как в HEAD (база снимается с принятого): правленое — из HEAD, неотслеживаемое — мимо.
    keep — файлы из базы: мерить всегда. Чужие черновики (неотслеживаемые _scratch*) — мимо, счётом foreign.
    """

    def __init__(self, root, exclude, committed=False, keep=()):
        self.root, self.sources, self.paths, self.ids, self.test_ids, self.skipped = root, {}, [], Counter(), Counter(), {}
        others = set("" if committed else (git(root, "ls-files", "-z", "--others", "--exclude-standard") or "").split("\0"))
        foreign = {p for p in others if re.match(r"_?scratch", os.path.basename(p), re.I)}
        listed, self.foreign = (git(root, "ls-files", "-z", check=True) or "").split("\0") + sorted(others - foreign), \
            sum(os.path.splitext(p)[1].lower() in LANGS for p in foreign)
        dirty = set((git(root, "diff", "--name-only", "-z", "--relative", "HEAD") or "").split("\0")) if committed else ()
        for path in sorted(set(p for p in listed if p)):
            parts, ext = path.split("/"), os.path.splitext(path)[1].lower()
            if any(p in SKIP_DIRS or p.startswith(".") for p in parts[:-1]) or parts[0] in SKIP_TOP and len(parts) > 1 \
                    or path in OWN_TOOLS or any(fnmatch.fnmatch(path, e) or path.startswith(e.rstrip("/") + "/")
                                                for e in exclude):
                continue
            self.paths.append(path)
            if ext not in LANGS and ext not in NAMES_ONLY:
                continue
            raw = split_lines(shown(root, "HEAD", path) or "") if path in dirty else read_lines(os.path.join(root, path))
            if not raw:
                continue
            ids = Counter(IDENT.findall("\n".join(raw)))
            self.ids.update(ids)
            if is_check(path):
                self.test_ids.update(ids)
            why = ext in LANGS and path not in keep and generated(path, raw)
            if ext in LANGS and not why:
                self.sources[path] = Source(path, raw, LANGS[ext])
            elif why:
                self.skipped[path] = why
        self.godot = "\n".join(read_lines(os.path.join(root, "project.godot")) or [])

    def code(self):
        return [(p, s) for p, s in self.sources.items() if s.lang != "shader"]


def section(ini, name):
    """Строки раздела [name] файла project.godot."""
    found = re.search(r"(?ms)^\[" + re.escape(name) + r"\]\s*$(.*?)(?=^\[|\Z)", ini or "")
    return found.group(1) if found else ""


def warn_levels(ini):
    return {k: int(v) for k, v in re.findall(r"(?m)^gdscript/warnings/(\w+)\s*=\s*(\d+)\s*$", section(ini, "debug"))}


def typed_by_engine(model):
    return warn_levels(model.godot).get("untyped_declaration", 0) >= 2


def hot_files(root, window):
    """Сколько из последних пунктов правили каждый файл — под нынешним именем; и сколько пунктов нашлось.

    Пункт — «Пункт|Item N:» своей партии, а не коммит (у [вид] их 3–6): номера в каждой партии свои, граница — коммит
    приёмки («Приёмка:», «Accept:», старые «Принять …») по журналу от новых к старым. Уборки («для игрока без
    изменений») не в счёт: их число уборка снизить не может, а она сама — правка файла.
    """
    log = git(root, "log", "-n", "400", "-M", "--format=%x01%s", "--name-status", "--", ".") or ""
    prefix = (git(root, "rev-parse", "--show-prefix") or "").strip()
    items, taken, alias, batch = defaultdict(set), set(), {}, 0
    for block in log.split("\x01")[1:]:
        lines = block.split("\n")
        rows = [row.split("\t") for row in lines[1:] if "\t" in row]
        alias.update({row[1]: alias.get(row[2], row[2]) for row in rows if row[0][:1] == "R" and len(row) == 3})
        batch += bool(re.match(r"(?:Accept|Приёмка|Принять)\b", lines[0]))
        item = re.match(r"(?:Пункт|Item) (\d+):", lines[0])
        key = (batch, item.group(1)) if item else None
        if item and (len(taken) < window or key in taken) and not re.search(
                r"no change for players|для игрока без изменений", lines[0]):
            taken.add(key)
            for r in (r for r in rows if r[-1].startswith(prefix)):
                items[alias.get(r[-1], r[-1])[len(prefix):]].add(key)
    return Counter({path: len(keys) for path, keys in items.items()}), len(taken)


def diff_path(text):
    """Путь из заголовка diff: без хвостового TAB (путь с пробелом), кавычек git (\\" и \\\\) и «a/» / «b/»."""
    text = re.sub(r"\\(.)", r"\1", text.rstrip("\t")[1:-1]) if text[:1] == '"' else text.rstrip("\t")  # quotepath=off
    return text[2:] if text[:2] in ("a/", "b/") else None


def shape(line, renamed=frozenset()):
    """Строка без чисел, текста в кавычках, приставок tree. и self. и имён, которые diff переименовал (renamed): правка
    только литералов или механическая правка переноса (_far → far, process_frame → tree.process_frame) её не меняет."""
    text = re.sub(r"\b(?:self|tree|get_tree\(\))\.", "", norm(line))
    text = IDENT.sub(lambda m: "0" if m.group(0) in renamed else m.group(0), text) if renamed else text
    return re.sub(r"\"[^\"]*\"|'[^']*'|(?<![\w.])\d[\d.]*", "0", text)


def changes(root, rev, model, to=None):
    """Новые значимые строки по файлам (с 0) без переносов, имена функций и методов с удалённых строк (dropped),
    перенесённые строки (добавленные, которые этот же diff удалил в другом месте), места удалений (строка, перед
    которой) и новые строки, у которых правлены только числа и текст или механически — имена, которые есть только
    по одну сторону diff, и приставка tree. (tuned: удалённая строка того же вида); to — до коммита.
    """
    diff = git(root, "diff", "-U0", "--no-color", "--no-ext-diff", "--src-prefix=a/", "--dst-prefix=b/",
               "--relative", rev, *[to] * bool(to), "--", ".") or ""
    added, removed, dropped, cuts, gone = defaultdict(list), Counter(), set(), defaultdict(set), []
    old = path = None
    left = right = right_at = 0
    for line in diff.split("\n"):
        if left and line.startswith("-"):
            if os.path.splitext(old or "")[1].lower() in LANGS:  # перенос — только из кода
                removed[norm(line[1:])] += 1
                gone.append(line[1:])
                dropped.update(n for pair in CALLABLE.findall(line[1:]) for n in pair if n)
            left -= 1
        elif right and line.startswith("+"):
            added[path].append((right_at, line[1:]))
            right_at, right = right_at + 1, right - 1
        elif line.startswith("--- "):
            old = diff_path(line[4:])
        elif line.startswith("+++ "):
            path = diff_path(line[4:])
        elif line.startswith("@@"):
            hunk = re.match(r"@@ -\d+(?:,(\d+))? \+(\d+)(?:,(\d+))?", line)
            left, right_at, right = int(hunk.group(1) or 1), int(hunk.group(2)) - 1, int(hunk.group(3) or 1)
            cuts[path].update([right_at + 1] if not right else [])
    untracked = (git(root, "ls-files", "-z", "--others", "--exclude-standard") or "").split("\0") if not to else []
    added.update({p: list(enumerate(model.sources[p].raw)) for p in untracked if p in model.sources})
    renamed = set(IDENT.findall("\n".join(gone))) ^ set(IDENT.findall("\n".join(l for v in added.values() for _, l in v)))
    new, shifted, tuned, shapes = {}, defaultdict(set), defaultdict(set), Counter(shape(line, renamed) for line in gone)
    for path, lines in added.items():
        src = model.sources.get(path)
        for index, line in (lines if src else []):
            if index < len(src.sig) and src.sig[index]:
                form = shape(line, renamed)
                moved, alike = removed[norm(line)] > 0, shapes[form] > 0
                removed[norm(line)] -= moved
                shapes[form] -= alike
                (shifted[path] if moved else new.setdefault(path, set())).add(index)
                tuned[path].update([index] if alike and not moved else [])
    return new, dropped, shifted, cuts, tuned


class Report:
    def __init__(self, diff, hot):
        self.findings, self.notes, self.diff, self.hot, self.over, self.excess = [], [], diff, hot, 0, 0

    def add(self, finding, weight, path, line, what, fix, over=False):
        """Строка находки или заметки; over — старое сверх порога находки (в --summary — «место»).

        Порядок — вес, затем файл и номер строки числом (не текстом: :105 после :1005 не встаёт).
        """
        where = path if line is None else f"{path}:{line + 1}"
        text = f"уборка: {where} — {what} — {fix}" + (" — этот diff" if finding and self.diff else "")
        (self.findings if finding else self.notes).append(((-weight * (1 + self.hot.get(path, 0)), path,
                                                            -1 if line is None else line), text))
        self.over += over


def number(value):
    return value[0] if isinstance(value, list) else value


def touched(new, path, start, end):
    return sum(1 for i in new.get(path, ()) if start <= i <= end)


def known_paths(base):
    """Файлы из базы (размер, функции, счётчики) — их мерят всегда."""
    return {k.split("::", 1)[0] for sec in ("files", "functions") + COUNTERS for k in (base or {}).get(sec, {})}


def base_stamp(root, base_path):
    """(коммит, где база менялась последний раз, путь базы от папки проекта); база вне проекта — ("", None)."""
    top, path = os.path.join(os.path.abspath(root), ""), os.path.abspath(base_path)  # relpath падает меж дисков
    rel = path[len(top):].replace("\\", "/") if os.path.normcase(path).startswith(os.path.normcase(top)) else None
    return ((git(root, "log", "-1", "--format=%H", "--", rel) or "").strip(), rel) if rel else ("", None)


def renames(model, base, stamp, rev):
    """Файлы базы, которых нет на месте: {новый путь: старый} — переименование или перенос в папку.

    Старый текст — из rev, коммита базы или HEAD; новый путь — файл вне базы, общих строк с которым не
    меньше половины большего из двух.
    """
    keyed = known_paths(base)
    gone = sorted(k for k in keyed if k not in model.sources)
    fresh, found = {p: {norm(x) for x in s.raw if x.strip()} for p, s in model.code() if gone and p not in keyed}, {}
    for old in gone:
        text = next((t for t in (shown(model.root, r, old) for r in (rev, stamp, "HEAD") if r) if t is not None), "")
        lines = {norm(x) for x in split_lines(text) if x.strip()}
        share, path = max(((len(lines & seen) / max(len(lines), len(seen)), p) for p, seen in fresh.items() if lines
                           and p not in found and os.path.splitext(p)[1] == os.path.splitext(old)[1]), default=(0, None))
        found.update({path: old} if share >= 0.5 else {})
    return found


def func_base(model, base, moved, revs):
    """Ключ базы каждой функции: запись с тем же отпечатком, если под своим ключом тело не то (перенос; новая
    одноимённая выше сдвинула «#2»), иначе своя, иначе ушедшая — того же имени в переименованном файле (сколько бы
    run() ни ушло разом); единственная неразобранная того же имени, тело которой (из первого коммита revs, где она
    есть) совпадает с нынешним хоть наполовину — перенос с правкой вызовов, и из удалённого файла. Новая run() с
    другим телом вместо удалённой — новая.
    """
    known, olds, result = base.get("functions", {}), {}, {}
    funcs = {f"{p}::{f['qual']}": f for p, s in model.code() for f in s.funcs}
    prints = {v[1]: k for k, v in known.items() if k not in funcs or funcs[k]["print"] != v[1]}
    for key, func in funcs.items():
        old = prints.get(func["print"])
        if old and old not in result.values() and known.get(key, (0, ""))[1] != func["print"]:
            result[key] = old
    result.update({k: k for k in funcs if k in known and k not in result and k not in result.values()})

    def alike(key, old):
        path, name = old.split("::", 1)
        for rev in (r for r in revs if r):
            if (rev, path) not in olds:
                text, lang = shown(model.root, rev, path), LANGS.get(os.path.splitext(path)[1].lower())
                olds[rev, path] = Source(path, split_lines(text), lang).funcs if text and lang else []
            was, now = next((f["lines"] for f in olds[rev, path] if f["qual"] == name), None), funcs[key]["lines"]
            if was is not None:
                return sum((Counter(was) & Counter(now)).values()) * 2 >= max(len(was), len(now))
        return False

    for stage in (1, 2):
        free = [k for k in known if k not in result.values()]
        names = Counter(k.split("::", 1)[1] for k in free)
        for key in [k for k in funcs if k not in result]:
            path, name = key.split("::", 1)
            old = f"{moved.get(path)}::{name}" if stage == 1 else \
                next((k for k in free if names[name] == 1 and k.endswith("::" + name) and alike(key, k)), None)
            result.update({key: old} if old in free and old not in result.values() else {})
    return result


SIZE_FIX = {"file": ("новое — своим файлом, здесь только вызов", "разнести на части — каждая меньше порога",
                     "разнести по частям перед пунктом, который его правит",
                     "перенесённое — отдельными файлами, каждый меньше порога"),
            "func": ("вынести шаг в функцию с именем",) * 3 + ("перенесённое — своей функцией, здесь только вызов",)}


def check_sizes(model, base, lim, diff, rep, moved, revs):
    """Н1 и Н2 — файлы и функции длиннее порога; заметки о больших файлах и функциях.

    С --changed судится выросшее против rev — новыми строками или перенесёнными (перенос в большой файл, помощник,
    влитый в длинную функцию); функции, которой в этом файле на rev не было, в рост идут только новые строки.
    Потолок — от меньшего из базы и размера на rev: место, освобождённое уборкой в партии, следующим пунктам не
    достаётся. Сверх потолка только вызов нового (call_lines новых строк, без перенесённых) — заметка, не находка;
    перерос перенесённым — «перенесённое — отдельно»; без --changed, какое новое, не видно — «разнести по частям».
    excess — строк сверх порога (--summary): у файла сверх порога — только его, излишек функций не прибавляется.
    revs — (rev, коммит базы, HEAD): где искать тело ушедшей функции (func_base).
    """
    files, funcs, rev, new = base.get("files", {}), base.get("functions", {}), revs[0], diff and diff[0]
    keys = func_base(model, base, moved, revs)

    def judge(kind, path, line, what, size, was, fresh, growth):
        """Сверх потолка — находка (только вызов нового — заметка); большое — заметка (с --changed — если выросло)."""
        top, note, fix = lim[kind + "_lines"], lim[f"note_{kind}_lines"], SIZE_FIX[kind]
        cap, carried = max(top, was + lim[kind + "_growth"] if was else 0), max(0, growth - fresh)
        limit, call = f"порог {top}" + (f", база {was}, допуск +{lim[kind + '_growth']}" if was else ""), \
            bool(was) and new is not None and fresh <= lim["call_lines"] and not carried
        if size > cap:
            rep.add(not call, size / top, path, line, f"{what[0]} длиннее нормы ({size} / {limit})" + ", сверх допуска"
                    " — только вызов нового" * call, fix[3] if carried and size - carried <= cap else fix[2] if call
                    or was and new is None else fix[0] if was else fix[1])
        elif size > note and (new is None or size - fresh <= note):
            rep.add(False, size / top, path, line, f"{what[1]} ({size} / "
                    f"{limit if was else f'заметка от {note}, порог {top}'})", fix[2], over=size > top)

    for path, src in model.code():
        was, fresh = files.get(path) or files.get(moved.get(path)), len(new.get(path, ())) if new else 0
        rep.excess += (max(0, src.size - lim["file_lines"]) or sum(max(0, f["size"] - lim["func_lines"])
                                                                   for f in src.funcs)) if new is None else 0
        changed = new is not None and any(path in lines for lines in (new, diff[2], diff[3]))  # и только удаления:
        # влитый помощник git показывает удалением его заголовка — граница функции сдвинулась, строки на месте
        text = (shown(model.root, rev, path) or path in moved and shown(model.root, rev, moved[path])) if changed else None
        then = Source(path, split_lines(text), src.lang) if text else None
        sizes = {f["qual"]: f["size"] for f in then.funcs} if then else {}
        growth = src.size - (then.size if then else 0) if changed else 0
        if new is None or growth > 0:
            judge("file", path, None, ("файл", "файл большой"), src.size, min(was, then.size) if was and then else was,
                  fresh, growth)
        for func in src.funcs:
            added, key = touched(new, path, func["start"], func["end"]) if new else 0, keys.get(f"{path}::{func['qual']}")
            grew = func["size"] - sizes.get(func["qual"], func["size"] - added) if changed else 0
            if new is None or grew > 0:
                judge("func", path, func["start"], (f"функция {func['qual']}", f"функция {func['qual']} большая"),
                      func["size"], min(funcs[key][0], sizes.get(func["qual"], funcs[key][0])) if key else None,
                      added, grew)


def window_key(seq, k, width):
    return digest("\n".join(s for _, s in seq[k:k + width]))


def windows(model, width):
    """Окна из width значимых строк: последовательности по файлам и повторы (хеш → места).

    Мимо — подключения: import, using, extends, `const X := preload(…)`, строки многострочного `import {…} from`.
    """
    seqs, places = {}, defaultdict(list)
    for path, src in model.sources.items():
        seq, block = [], False
        for i in (i for i in range(len(src.raw)) if src.sig[i]):
            s = norm(src.text[i])
            opens = not block and re.match(r"(?:import|export)(?: type)? ?(?:[\w$]+, ?)?\{[^}]*$", s)
            if block or opens:
                block = bool(opens) or "}" not in s
            elif re.search(r"\w", s) and not re.match(r"(?:(?:import|from|using|extends|class_name)\b|#include\b|export "
                                                      r"\{|(?:const|var) \w+ ?:?= ?(?:pre)?load\()", s):
                seq.append((i, s))
        seqs[path] = seq
        for k in range(len(seq) - width + 1):
            key = window_key(seq, k, width)
            last = places[key][-1] if places[key] else None
            if not (last and last[0] == path and k - last[1] < width):
                places[key].append((path, k))
    return seqs, {key: spots for key, spots in places.items() if len(spots) > 1}


def runs(pairs):
    """Цепочки соседних совпавших окон пары мест: (a, i, b, j, окон) — повтор целиком."""
    for a, i, b, j in sorted(pairs):
        if (a, i - 1, b, j - 1) not in pairs:
            run = 1
            while (a, i + run, b, j + run) in pairs:
                run += 1
            yield a, i, b, j, run


def carried(seqs, diff, spots, size):
    """Места повтора по size строк: True — перенос, а не новая копия: ни в одном месте нового (diff — changes()) не
    больше перенесённого, и хоть одно место diff задел — перенос с правкой (root → tree.root) или удаление между
    строками (соседние куски сошлись после уборки); False — новая копия; None — diff их не задел.
    """
    new, _, shifted, cuts = diff[:4]
    touched = False
    for path, k in spots:
        rows = [seqs[path][j][0] for j in range(k, k + size)]
        fresh, kept = (sum(i in lines.get(path, ()) for i in rows) for lines in (new, shifted))
        if fresh > kept:
            return False
        touched = touched or kept or any(rows[0] < cut <= rows[-1] for cut in cuts.get(path, ()))
    return True if touched else None


def joined_repeats(seqs, dups, diff, width):
    """Ключи повторов из базы, задетых переносом, — одно правило для --changed, --tighten и Н10 (подъём базы).

    Судится повтор целиком — цепочка окон пары мест (carried по всем её строкам), а не окно: иначе окна одного
    куска, перенесённого с правкой, расходились бы. Ключ — по всем своим парам: новой копии нет ни в одной, хоть
    одна задета. Копия, пережившая прошлый /studio/done, не задета — так и остаётся находкой.
    """
    verdicts = defaultdict(set)
    for a, i, b, j, run in runs({spots[0] + other for spots in dups.values() for other in spots[1:]}):
        verdict = carried(seqs, diff, [(a, i), (b, j)], run + width - 1)
        for r in range(run):
            verdicts[window_key(seqs[a], i + r, width)].add(verdict)
    return {key for key, seen in verdicts.items() if True in seen and False not in seen}


def check_repeats(base, lim, diff, rep, seqs, dups, joined):
    """Н3 — повтор блока: с --changed — хоть одна сторона новая; без — мест больше, чем в базе.

    Повтор из базы, задетый переносом (joined: с --changed — этим diff, без — с коммита базы), и соседние куски,
    сошедшиеся после уборки, — заметка; --tighten вносит их в базу.
    """
    width, known, new = lim["repeat_lines"], base.get("repeats", {}), diff and diff[0]

    def fresh(path, k):
        return new is not None and any(seqs[path][j][0] in new.get(path, ()) for j in range(k, k + width))

    pairs = set()
    for key, spots in dups.items():
        if len(spots) > known.get(key, 0) if new is None else any(fresh(p, k) for p, k in spots):
            pairs.update(spots[0] + other for other in spots[1:])
    for a, i, b, j, run in runs(pairs):
        if fresh(a, i) and not fresh(b, j):
            a, i, b, j = b, j, a, i
        size, origin, other = run + width - 1, f"{a}:{seqs[a][i][0] + 1}", f"{b}:{seqs[b][j][0] + 1}"
        old = all(window_key(seqs[a], i + r, width) in joined for r in range(run))
        if new is None:  # какая сторона новая, не знаем — обе поимённо
            rep.add(not old, size / width, a, seqs[a][i][0], f"повтор {size} строк: здесь и в {other}" + " — из базы, "
                    "задет переносом" * old + f" ({size} / порог {width})", "оставить одно место, во втором — вызов")
        else:
            rep.add(not old, size / width, b, seqs[b][j][0], f"повтор {size} строк с {origin}" + " — из базы, задет"
                    " переносом" * old + f" ({size} / порог {width})", f"вызвать {origin}")


def helpers(model, lim):
    """Одноимённые функции с тем же телом в разных файлах: «имя:отпечаток» → [(файл, функция)]."""
    groups = defaultdict(list)
    for path, src in model.code():
        for func in src.funcs:
            if func["body"] >= lim["helper_lines"]:
                groups[f"{func['name']}:{func['print']}"].append((path, func))
    return {key: items for key, items in groups.items() if len(set(p for p, _ in items)) > 1}


def check_helpers(base, new, rep, groups):
    """Н4 — одноимённый помощник с тем же телом в двух файлах; с --changed — задетый этим diff, но у копии из базы,
    где правлен только заголовок (export, static), — заметка: файлов не прибавилось."""
    known = base.get("helpers", {})
    for key, items in groups.items():
        files = len(set(p for p, _ in items))
        fresh = [(p, f) for p, f in items if new is not None and touched(new, p, f["start"], f["end"])]
        if (files > known.get(key, 0)) if new is None else fresh:
            path, func = (fresh or items)[-1]
            other = next(p for p, _ in items if p != path)
            old = new is not None and files <= known.get(key, 0) and not any(
                touched(new, p, f["start"] + 1, f["end"]) for p, f in fresh)
            rep.add(not old, files, path, func["start"], f"помощник {func['name']} — то же тело, что в {other}"
                    + " — из базы, задет заголовок" * old + f" (файлов {files} / порог 1)",
                    "вынести в общий файл, в обоих местах — вызов")


def split_params(code, pos):
    """Параметры от открывающей скобки до парной и остаток строки после неё."""
    depth, cuts = 1, [pos - 1]
    for k in range(pos, len(code)):
        depth += (code[k] in "([{") - (code[k] in ")]}")
        if depth == 0 or code[k] == "," and depth == 1:
            cuts.append(k)
        if depth == 0:
            return [p for p in (code[a + 1:b].strip() for a, b in zip(cuts, cuts[1:])) if p], code[k + 1:]
    return [], ""


def declared(code):
    """Имена, объявленные в логической строке GDScript (var, const, параметры func): [(имя, тип)] — тип True или
    False, у `:= Класс.ИМЯ` — (Класс, ИМЯ): тип того объявления."""
    found = [(m.group(1), m.group(2)) for m in re.finditer(r"\b(?:var|const)\s+(\w+)(.*)", code)]
    for func in re.finditer(r"\bfunc\b\s*\w*\s*\(", code):
        found += [m.groups() for m in (re.match(r"(\w+)(.*)", p) for p in split_params(code, func.end())[0]) if m]
    aliases = [re.match(r"[ \t]*:=[ \t]*([A-Z]\w*)\.(\w+)[ \t]*$", rest) for _, rest in found]
    return [(name, alias.groups() if alias else bool(DECL_TYPED.match(rest))) for (name, rest), alias in zip(found, aliases)]


def untyped(src, typed_calls, typed_of):
    """Н5: объявления GDScript без типа — var, параметр, возврат func, переменная цикла.

    Цикл по имени — по его объявлению: ближнему выше в той же функции, иначе вне функций этого файла или его предков
    по extends (typed_of). Прочие файлы счёт не меняют: удалённый где-то псевдоним или параметр того же имени не
    отнимают тип; функция, перенесённая целиком к тем же предкам, — тоже.
    """
    marks, lines, decl, home = [], logical(src), defaultdict(list), {}
    for func in sorted(src.funcs, key=lambda f: f["start"]):  # строка → начало своей функции
        home.update(dict.fromkeys(range(func["start"], func["end"] + 1), func["start"]))
    for start, _, _, code in lines:
        for name, typed in declared(code) if home.get(start) is not None else ():
            decl[name].append((start, typed))

    def typed_name(name, line):
        scope = home.get(line)
        near = [t for at, t in decl.get(name, ()) if at <= line and scope is not None and home.get(at) == scope]
        return typed_of(src.path, name, near[-1] if near else None)

    for start, _, _, code in lines:
        var = GD_VAR.match(code)
        if var and var.group(2) in (None, "="):
            marks.append((start, f"var {var.group(1)}"))
        for func in re.finditer(r"\bfunc\b\s*(\w*)\s*\(", code):
            params, rest = split_params(code, func.end())
            marks += [(start, f"параметр {p.split('=')[0].strip()}") for p in params
                      if not p.startswith("...") and not re.match(r"\w+\s*:", p)]
            if not re.match(r"\s*->", rest):
                marks.append((start, f"возврат {func.group(1) or 'лямбды'}"))
        loop = re.match(r"\s*for\s+(\w+)\s+in\s+(.+?)\s*:(?:\s|$)", code)
        it = loop.group(2) if loop else ""
        call = re.search(r"(\w+)\([^()]*\)$", it)
        if loop and not (INT_LOOP.search(it) or re.fullmatch(r"\w+", it) and typed_name(it, start)
                         or call and call.group(1) in typed_calls):
            marks.append((start, f"for {loop.group(1)}"))
    return marks


def private_access(src):
    """Н6: проверка обращается к закрытому — obj._имя, .call("_…"), .get(&"_…")."""
    marks = []
    for i, code in enumerate(src.code):
        for hit in re.finditer(r"\._[A-Za-z]\w*", code):
            before = code[:hit.start()].rstrip()
            if not re.search(r"\b(?:self|super|this|cls)$|super\(\)$", before) and re.search(r"[\w)\]]$", before):
                marks.append((i, hit.group(0)))
        if PRIVATE_CALL.search(src.text[i]):
            marks.append((i, PRIVATE_CALL.search(src.text[i]).group(0)))
    return marks


def counters(model):
    """Места Н5–Н7 по видам и файлам: {вид: {файл: [(строка, что)]}}."""
    found = {kind: {} for kind in ("untyped", "private", "byname")}
    names, members, parents, classes, loads = set(), defaultdict(dict), {}, {}, defaultdict(dict)
    engine = typed_by_engine(model)
    for path, src in model.sources.items():
        if src.lang == "gd":
            names.update(re.findall(r"\bfunc\s+(\w+)", "\n".join(src.code)))
            inside = {i for f in src.funcs for i in range(f["start"], f["end"] + 1)}
            for start, _, indent, code in [] if engine else logical(src):  # вне функций: объявления, предок,
                if start in inside:                                          # class_name, const X := preload(…)
                    continue
                members[path].update(declared(code))
                text = "" if indent else src.text[start]
                head = re.match(r"\s*(?:class_name\s+(\w+)\s*)?(?:extends\s+(?:(\w+)|[\"']res://([^\"']+)))?", text)
                load = re.match(r"\s*const\s+(\w+)\s*:?=\s*preload\(\s*[\"']res://([^\"']+)[\"']", text)
                classes.update({head.group(1): path} if head.group(1) else {})
                parents.update({path: head.group(2) or head.group(3)} if head.group(2) or head.group(3) else {})
                loads[path].update([load.groups()] if load else [])
        elif src.lang == "cs":
            names.update(re.findall(r"\bpublic\b[^;{}=()]*?\b(\w+)\s*(?:<[^<>()]*>)?\s*\(", "\n".join(src.code)))
    typed_calls = TYPED_CALLS | set(re.findall(TYPED_RETURN, "\n".join(
        "\n".join(s.code) for s in model.sources.values() if s.lang == "gd")))

    def typed_of(path, name, value=None, seen=()):
        """Тип имени: value — объявление в функции, иначе вне функций файла path и его предков (extends); `:= Класс.ИМЯ`
        — как у ИМЯ в файле класса (class_name или `const Класс := preload(…)` рядом; класс не проекта, Vector3.UP,
        — с типом); не нашлось — без типа."""
        home = path
        while value is None and path in members and path not in seen:
            seen += (path,)
            home, value, path = path, members[path].get(name), classes.get(parents.get(path), parents.get(path))
        if isinstance(value, tuple):
            owner = loads[home].get(value[0]) or classes.get(value[0])
            return owner is None or typed_of(owner, value[1], None, seen)
        return bool(value)

    for path, src in model.code():
        if src.lang == "gd" and not engine:
            found["untyped"][path] = untyped(src, typed_calls, typed_of)
        if is_test(path) and src.lang != "py":  # в Python sys._getframe, os._exit — не чужое закрытое
            found["private"][path] = private_access(src)
        if src.lang in ("gd", "cs"):
            found["byname"][path] = [(i, m.group(1)) for i, text in enumerate(src.text)
                                     for m in BYNAME.finditer(text) if m.group(1) not in names]
    return {kind: {p: marks for p, marks in per_file.items() if marks} for kind, per_file in found.items()}, names


COUNTER_TEXT = {"untyped": ("объявлений без типа", "дописать тип"), "byname": ("вызов по имени, которого нет", ""),
                "private": ("проверка лезет в закрытое", "открытый метод или ввод")}


def check_counters(model, base, diff, rep, found, names, moved):
    """Н5–Н7 — сверх итога базы (перенос между файлами не в счёт); с --changed ещё места на новых строках и вызовы по
    имени, которое этот diff удалил.

    С --changed старые строки Н5 судятся итогом, как без флагов: тип им могла отнять правка в другом файле (у предка
    снят тип, у функции — тип возврата); Н7 — вызовы имён, чьи объявления diff удалил (переименован метод C#); Н6 от
    других файлов не зависит. Н5 и Н6 на старой строке, где правлены только числа, текст или имена переноса (tuned),
    — заметка: объявление или обращение не новое, в итоге оно старое.
    """
    new, dropped, tuned = (diff[0], diff[1], diff[4]) if diff else (None, set(), {})
    cs_names = sorted(n for n in names if n[:1].isupper())
    for kind, per_file in found.items():
        known, what, fix = base.get(kind, {}), *COUNTER_TEXT[kind]
        fresh, old = defaultdict(list), defaultdict(list)
        for path, marks in per_file.items():
            for line, name in marks:
                recent = new is not None and (line in new.get(path, ()) or kind == "byname" and name in dropped)
                if recent and kind != "byname" and line in tuned.get(path, ()):
                    rep.add(False, 0.5, path, line, f"{what}: {name} — старое "
                            f"{dict(private='обращение', untyped='объявление')[kind]}, правлены числа, текст или имена "
                            "переноса", fix)
                    recent = False
                (fresh if recent else old)[path].append((line, name))
        over = (new is None or kind == "untyped") and sum(map(len, old.values())) > sum(known.values())
        for path, marks, was, aged in [(p, v, 0, "") for p, v in fresh.items()] + [
                (p, v, known.get(p, known.get(moved.get(p), 0)), " в старых строках" * (new is not None))
                for p, v in old.items() if over]:
            if len(marks) <= was:
                continue
            if was:  # какие из мест новые, не знаем — только число
                rep.add(True, len(marks) - was, path, None, f"{what}{aged}: на {len(marks) - was} больше базы "
                        f"({len(marks)} / порог 0, база {was})", fix or "поправить имя")
            elif kind == "byname":
                for line, name in marks:
                    like = difflib.get_close_matches(name, cs_names, n=1, cutoff=0.6)
                    rep.add(True, 1, path, line, f"{what}: «{name}»",
                            f"в C# есть {like[0]}" if like else "такого метода нет ни в C#, ни в GDScript — поправить имя")
            else:
                sample = ", ".join(m[1] for m in marks[:3]) + (" …" if len(marks) > 3 else "")
                rep.add(True, len(marks), path, marks[0][0], f"{what}{aged}: {sample} ({len(marks)} / порог 0)", fix)


def shown(root, rev, path):
    """Файл в коммите rev (путь от папки проекта); None — нет."""
    return git(root, "show", f"{rev}:./{path}", check=True)


def architecture(root):
    text = "\n".join(read_lines(os.path.join(root, "docs", "CONCEPT.md")) or [])
    head = re.search(r"(?m)^(#{1,6})\s*Архитектура.*$", text)
    rest = text[head.end():] if head else ""
    return rest[:re.search(r"(?m)^#{1,%d}\s|\Z" % len(head.group(1)), rest).start()] if head else ""


def check_rules(model, rev, new, rep):
    """Н8 — ослаблены типы против rev; Н9 — новая служба [autoload] без записи в «Архитектуре».

    @warning_ignore тех ключей, которые этот же diff поднял, — не ослабление: так включают по папкам.
    Н9 с --changed — заметка: CONCEPT.md исполнителю не править, запись вносит /studio/done из его строки
    `CONCEPT, Службы` (её сверяет проверяющий).
    """
    root, fix, raised = model.root, "вернуть как было — типы не ослаблять", set()
    old_ini = shown(root, rev, "project.godot")
    if old_ini is not None:
        now, was = warn_levels(model.godot), warn_levels(old_ini)
        raised = {key for key, level in now.items() if level > was.get(key, 0)}
        for key, level in was.items():
            if now.get(key, 0) < level:
                rep.add(True, 1, "project.godot", None, f"ослаблены типы: gdscript/warnings/{key} {level} → "
                        f"{now.get(key, 0)}", fix)
        names = set(re.findall(r"(?m)^(\w+)\s*=", section(model.godot, "autoload")))
        arch = architecture(root)
        for name in sorted(names - set(re.findall(r"(?m)^(\w+)\s*=", section(old_ini, "autoload")))):
            if not re.search(r"\b" + re.escape(name) + r"\b", arch):
                rep.add(new is None, 1, "project.godot", None, f"служба {name} без записи в «Архитектуре» docs/CONCEPT"
                        ".md", "строкой в «Архитектуру» или узлом сцены" if new is None else
                        f"в итоге, в «В документы при /studio/done» — `CONCEPT, Службы: {name} — <что хранит>`")
    for path in (p for p in model.paths if p.endswith(".csproj")):
        old, now = shown(root, rev, path) or "", "\n".join(read_lines(os.path.join(root, path)) or [])
        for tag, value in (("Nullable", "enable"), ("TreatWarningsAsErrors", "true")):
            if re.search(rf"<{tag}>\s*{value}\s*<", old, re.I) and not re.search(rf"<{tag}>\s*{value}\s*<", now, re.I):
                rep.add(True, 1, path, None, f"ослаблены типы: <{tag}> больше не {value}", fix)
    for path, lines in (new or {}).items():
        src = model.sources[path]
        for i in sorted(lines):  # директива C# и аннотация GDScript — не в строках и комментариях
            if src.lang == "cs" and re.match(r"\s*#nullable\s+disable\b", src.code[i]) or src.lang == "gd" and \
                    IGNORE_TYPES.search(src.text[i]) and not set(re.findall(r"untyped_declaration|unsafe_\w+",
                                                                            src.text[i])) <= raised:
                rep.add(True, 1, path, i, f"ослаблены типы: {src.raw[i].strip()[:60]}", fix)


def check_raised(model, rev, rel, base, rep, joined):
    """Н10 — база выше, чем в rev: итог счётчиков, новая запись (кроме перенесённой), порог, exclude.

    Новые разделы — от --add-new-metrics — не в счёт; запись под новым ключом — не подъём, если ушла
    запись не меньше (у файла — которого больше нет, у функции — с тем же отпечатком или именем), а у
    повтора (новый ключ или больше мест) — если joined(ключ): повтор из базы, задетый с rev (joined_repeats; без
    --changed rev — HEAD, и такой повтор в незакоммиченной базе — только от --tighten).
    """
    old = as_base(shown(model.root, rev, rel)) if rel else None
    if old is None:
        return
    fix, rule = "базу поднимать нельзя — вернуть числа", "только пунктом очереди о порогах, с причиной — назвать в итоге"
    for sec in (s for s in SECTIONS if s in old):
        now_sec, was_sec = base.get(sec, {}), old[sec]
        if sec in COUNTERS:  # счётчики — итогом: перенос между файлами не подъём
            now_sec, was_sec = {"итог": sum(now_sec.values())}, {"итог": sum(was_sec.values())}
        credit = {k: v for k, v in was_sec.items() if k not in now_sec and (sec == "functions" or sec == "files"
                                                                             and k not in model.sources)}
        for key, value in now_sec.items():
            now, was = number(value), number(was_sec.get(key))
            moved = was is None and next((k for k, v in credit.items() if number(v) >= now and (
                sec == "files" or v[1] == value[1] or k.split("::", 1)[1] == key.split("::", 1)[1])), None)
            if moved:
                del credit[moved]
            elif (was is None or now > was) and not (sec == "repeats" and joined(key)):
                rep.add(True, 1, rel, None, f"база поднята: {sec} «{key}» {was if was is not None else 'нет'} → {now}",
                        fix)
    for key, value in base.get("limits", {}).items():
        if value > old.get("limits", {}).get(key, LIMITS.get(key, (value,))[0]):
            rep.add(True, 1, rel, None, f"база поднята: порог {key} до {value}", rule)
    for item in sorted(set(base.get("exclude", [])) - set(old.get("exclude", []))):
        rep.add(True, 1, rel, None, f"база поднята: из замера исключено {item}", rule)


def note_classes(model, lim, new, rep):
    """Класс с множеством полей или открытых методов; с --changed — только перешедший порог этим diff."""
    for path, src in model.code():
        for cls in src.classes:
            grown = sum(1 for i in cls["decl"] if i in new.get(path, ())) if new is not None else 0
            if new is not None and (not grown or cls["fields"] - grown > lim["class_fields"]
                                    or cls["methods"] - grown > lim["class_methods"]):
                continue
            if cls["fields"] > lim["class_fields"] or cls["methods"] > lim["class_methods"]:
                rep.add(False, max(cls["fields"] / lim["class_fields"], cls["methods"] / lim["class_methods"]),
                        path, cls["start"], f"класс {cls['name']}: полей {cls['fields']}, открытых методов "
                        f"{cls['methods']} (заметка от {lim['class_fields']} и {lim['class_methods']})",
                        "запись или часть — своим типом")


def note_numbers(model, new, rep):
    """Одинаковый набор из двух и больше дробных чисел в двух файлах (0, 1, 0.5, 2 не в счёт)."""
    sets = defaultdict(list)
    for path, src in model.sources.items():
        for i, code in enumerate(src.code):
            values = [v for v in FLOAT.findall(code) if float(v) not in (0.0, 1.0, 0.5, 2.0)]
            if len(set(float(v) for v in values)) > 1:  # (10.0, 10.0) — одно число, не набор
                sets[tuple(float(v) for v in values)].append((path, i, values))
    for spots in sets.values():
        files = sorted(set(s[0] for s in spots))
        fresh = [s for s in spots if new is not None and s[1] in new.get(s[0], ())]
        if len(files) > 1 and (new is None or fresh):
            path, line, values = (fresh or spots)[0]
            other = next(f"{p}:{i + 1}" for p, i, _ in spots if p != path)
            rep.add(False, len(files) / 2, path, line, f"набор чисел ({', '.join(values[:4])}{' …' * (len(values) > 4)})"
                    f" ещё в {other} (файлов {len(files)})", "одно определение с именем, остальные берут его")


def declarations(model):
    """Объявления, которые ищутся по тексту проекта: (файл, строка, имя, открытое)."""
    found = []
    for path, src in model.code():
        if src.lang == "gd":
            found += [(path, f["start"], f["name"], f["public"]) for f in src.funcs]
            found += [(path, i, m.group(1), True) for i, c in enumerate(src.code)
                      for m in [re.match(r"(?:static\s+)?const\s+(\w+)", c)] if m]
        elif src.lang == "cs" and not re.search(r"\bclass\s+\w+[^{]*:[^{]*\bI[A-Z]\w*", "\n".join(src.code)):
            for i, code in enumerate(src.code):
                found += [(path, i, m.group(1), True) for m in PUBLIC_CS.finditer(code)]
                const = re.search(r"\b(?:const|static\s+readonly)\s+[\w<>\[\],.?]+\s+(\w+)\s*=", code)
                found += [(path, i, const.group(1), "public" in code)] if const else []
        elif src.lang in ("py", "js"):
            rx = r"(?:async\s+)?def\s+(\w+)|([A-Z][A-Z0-9_]+)\s*=" if src.lang == "py" else \
                r"(?:export\s+)?(?:async\s+)?function\s*\*?\s*(\w+)"
            found += [(path, i, m.group(1) or m.group(m.lastindex), not m.group(m.lastindex).startswith("_"))
                      for i, c in enumerate(src.code) for m in [re.match(rx, c)] if m]
    return [d for d in found if d[2] not in VIRTUALS and not d[2].startswith(("_on_", "test", "_test", "__"))
            and d[2] != "main"]


def note_dead(model, new, rep):
    """Мёртвое: имени больше нигде в тексте проекта нет; открытое, которое зовут только проверки.

    Файл зовёт по собранному имени (call("_" + layer)) — его имена с этой приставкой не мёртвые.
    """
    decls = declarations(model)
    total = Counter(d[2] for d in decls)
    outside = Counter(d[2] for d in decls if not is_test(d[0]))
    built = {p: re.findall(r"""(?:\b(?:call|callv|call_deferred|has_method)\(|Callable\([^,()]*,)\s*&?["'](\w*)"""
                           r"""[^"'\n]*["']\s*[+%]""", "\n".join(src.text)) for p, src in model.code()}
    for path, line, name, public in decls:
        if new is not None and line not in new.get(path, ()) or any(name.startswith(b) for b in built.get(path, ())):
            continue
        if model.ids[name] <= total[name]:
            rep.add(False, 1, path, line, f"мёртвое: {name} — больше нигде не упоминается", "удалить")
        elif public and not is_test(path) and model.test_ids[name] and \
                model.ids[name] - model.test_ids[name] <= outside[name]:
            rep.add(False, 0.5, path, line, f"{name} зовут только проверки", "удалить или подключить")


def note_design(model, new, rep):
    """Переусложнение: базовый класс с одним наследником, class_name с одной ссылкой."""
    heirs, declared = Counter(), {}
    for path, src in model.code():
        for i, code in enumerate(src.code):
            named = re.match(r"\s*class_name\s+(\w+)", code) if src.lang == "gd" else re.search(
                r"\bclass\s+(\w+)(?:\s*<[^>]*>)?\s*(?:\(\s*(\w+)|:\s*(\w+)|\s+extends\s+(\w+))?", code)
            if named:
                declared[named.group(1)] = (path, i, src.lang)
                heirs.update(g for g in named.groups()[1:] if g)
            parent = re.match(r"\s*(?:class\s+\w+\s+)?extends\s+(\w+)", code) if src.lang == "gd" else None
            heirs.update([parent.group(1)] if parent else [])
    for name, (path, line, lang) in declared.items():
        if new is not None and line not in new.get(path, ()):
            continue
        if heirs[name] == 1:
            rep.add(False, 0.5, path, line, f"базовый класс {name} с одним наследником", "слить с наследником")
        elif lang == "gd" and model.ids[name] <= 2:
            rep.add(False, 0.3, path, line, f"class_name {name}: ссылок {max(0, model.ids[name] - 1)}", "убрать class_name")


def note_lines(model, lim, new, rep):
    """По строкам: Dictionary без типов, обращение вверх по дереву, ссылки на пункты очереди, комментарии."""
    autoload = {p.split("res://", 1)[-1] for p in re.findall(r'"\*?(res://[^"]+)"', section(model.godot, "autoload"))}
    rules = (("untyped_dict", "Dictionary без типов", "запись — классом, коллекция — Dictionary[K, V]"),
             ("uptree", "обращение вверх по дереву", "сигнал или ссылка от родителя"),
             ("queue", "ссылки на пункты очереди", "ссылку — на постоянный документ, историю — в DECISIONS.md"))
    for path, src in model.code():
        godot_dict = src.lang == "cs" and any(line.strip() == "using Godot.Collections;" for line in src.raw)
        hits = defaultdict(list)
        for i, text in enumerate(src.text):
            if new is not None and i not in new.get(path, ()):
                continue
            if src.lang == "gd" and re.search(r"->\s*Dictionary\s*:", src.code[i]) or src.lang == "cs" and (
                    "public" not in text and ("Godot.Collections.Dictionary" in text
                                              or godot_dict and re.search(r"\bDictionary\b(?!\s*<)", text))):
                hits["untyped_dict"].append(i)
            if src.lang in ("gd", "cs") and (UPTREE.search(text) or path not in autoload and re.search(r"[\"']/root/", text)):
                hits["uptree"].append(i)
            if QUEUE_REF.search(src.raw[i]) and not QUEUE_REF.search(text):  # в комментарии, не в строке
                hits["queue"].append(i)
        for key, what, fix in rules:
            if hits[key]:
                rep.add(False, len(hits[key]) / 20, path, hits[key][0], f"{what}: {len(hits[key])}", fix)
        share = sum(src.note) * 100 // max(1, sum(src.note) + src.size)
        if new is None and src.size >= 50 and share > lim["comment_share"]:
            rep.add(False, 0.2, path, None, f"комментарии — {share}% строк (заметка — больше {lim['comment_share']}%)",
                    "историю — в git и DECISIONS.md, в коде — почему сейчас так")


def note_project(model, lim, rep, found):
    """Заметки о проекте целиком: типы движка (мало — одной уборкой, много — по папкам), C#, большие папки."""
    if model.godot and any(s.lang == "gd" for s in model.sources.values()) and not typed_by_engine(model):
        folders, parts = Counter(), Counter()  # папка больше types_batch — по файлам
        for path, marks in found["untyped"].items():
            folders[path.split("/")[0] + "/" if "/" in path else "./"] += len(marks)
        for path, marks in found["untyped"].items():
            top = path.split("/")[0] + "/" if "/" in path else "./"
            parts[path if folders[top] > lim["types_batch"] else top] += len(marks)
        count = sum(folders.values())
        for where, n in parts.most_common() if count >= lim["types_batch"] else [("типы", count)]:
            what = f"{n} {plural(n, 'объявление', 'объявления', 'объявлений')} без типа"
            rep.add(False, 0.3, where, None, what if where == "типы" else "типы: " + what, (
                "дописать; " * bool(n) if where == "типы" else "дописать здесь; когда все папки чисты — ") +
                "включить untyped_declaration=2 («Здоровье кода» docs/TESTING.md); unsafe_* — потом, уборками по "
                "папкам: их число — load_all.gd под пробными ключами, бывает в разы больше")
    csproj = [p for p in model.paths if p.endswith(".csproj")]
    if csproj and not any(re.search(r"<Nullable>\s*enable", "\n".join(read_lines(os.path.join(model.root, p)) or []),
                                    re.I) for p in csproj):
        loose = sum(1 for s in model.sources.values() if s.lang == "cs"
                    and not any(re.match(r"\s*#nullable\s+enable\b", c) for c in s.code[:40]))
        if loose:
            rep.add(False, 0.3, "C#", None, f"без `#nullable enable` — файлов .cs: {loose}",
                    "по файлу, перед пунктом, который его правит; новые — сразу с ним («Здоровье кода» docs/TESTING.md)")
    folders = Counter(os.path.dirname(p) or "." for p, _ in model.code())
    for folder, count in folders.items():
        if count > lim["folder_files"]:
            rep.add(False, count / lim["folder_files"], folder + "/", None,
                    f"папка: файлов кода {count} (заметка от {lim['folder_files']})", "разложить по подпапкам систем")


def limits_of(base):
    own = {k: v for k, v in (base or {}).get("limits", {}).items() if k in LIMITS and isinstance(v, int)}
    return {k: own.get(k, v[0]) for k, v in LIMITS.items()}, own


def snapshot(model, lim, wins=None):
    """Числа для базы: всё сверх порогов сейчас — только числа и отпечатки; wins — готовые windows()."""
    state = {sec: {} for sec in SECTIONS}
    for path, src in model.code():
        if src.size > lim["file_lines"]:
            state["files"][path] = src.size
        for func in src.funcs:
            if func["size"] > lim["func_lines"]:
                state["functions"][f"{path}::{func['qual']}"] = [func["size"], func["print"]]
    state["repeats"] = {k: len(v) for k, v in (wins or windows(model, lim["repeat_lines"]))[1].items()}
    state["helpers"] = {k: len(set(p for p, _ in v)) for k, v in helpers(model, lim).items()}
    state.update({kind: {p: len(v) for p, v in per_file.items()} for kind, per_file in counters(model)[0].items()})
    return state


def save(path, base):
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    rows, dump = [], lambda value: json.dumps(value, ensure_ascii=False)
    for key, value in sorted(base.items()):  # запись на строку — diff базы читается
        inner = ",\n".join(f"  {dump(k)}: {dump(value[k])}" for k in sorted(value)) if isinstance(value, dict) else ""
        rows.append(f" {dump(key)}: " + ("{\n" + inner + "\n }" if inner else dump(value)))
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("{\n" + ",\n".join(rows) + "\n}\n")


def write_base(model, base_path, base, add_new):
    """--baseline: записать нынешнее; с --add-new-metrics — дописать только разделы, которых нет."""
    lim, _ = limits_of(base)
    state = snapshot(model, lim)
    base = base or {"version": VERSION, "date": datetime.date.today().isoformat(), "limits": {}, "exclude": []}
    added, base["version"] = [sec for sec in SECTIONS if sec not in base], max(VERSION, base.get("version", 0))
    for sec in added:
        base[sec] = state[sec]
    save(base_path, base)
    sizes = ", ".join(f"{sec} {len(base[sec])}" for sec in added) or "новых метрик нет"
    print(f"База {'записана' if added == list(SECTIONS) else 'дополнена'}: {sizes}.\n"
          f"Итог: база {base['date']} — {base_path}.")
    return 0


def tighten(model, base_path, base):
    """--tighten: снизить числа, где стало лучше; убрать исправленное; перенесённое — под новым ключом.

    Поднимать не умеет. Счётчики Н5–Н7: итог не вырос — раздел по файлам заново (перенос между файлами); вырос —
    раздел не трогать и по файлам: снизив одни файлы, база осталась бы ниже и после отката виновника.
    Новый повтор или больше мест у повтора — только повтор из базы, задетый с прошлой базы (joined_repeats):
    соседние куски, сошедшиеся после уборки, или перенос с правкой; новая копия в базу не идёт и видна полным
    прогоном, пока её не уберут.
    """
    lim, stamp = limits_of(base)[0], base_stamp(model.root, base_path)[0]
    (seqs, dups), changed = windows(model, lim["repeat_lines"]), []
    state, moved = snapshot(model, lim, (seqs, dups)), renames(model, base, stamp, "HEAD")
    moves = [(sec, old, path) for path, old in moved.items()
             for sec in ("files",) + COUNTERS if old in base.get(sec, {}) and path not in base[sec]]
    renamed = moves + [("functions", old, key) for key, old in func_base(model, base, moved, (stamp, "HEAD")).items()
                       if key != old]
    for sec, key, value in [(sec, key, base[sec].pop(old)) for sec, old, key in renamed]:  # «#2» ↔ «#1» — разом
        base[sec][key] = value
    changed += [f"{sec} «{old}» перенесено → {key}" for sec, old, key in renamed]
    grown = {sec for sec in COUNTERS if sum(state[sec].values()) > sum(base.get(sec, {}).values())}
    for sec in COUNTERS:
        was, now = base.get(sec), state[sec]
        if was is not None and was != now and sec not in grown:
            base[sec] = now
            changed.append(f"{sec}: итог {sum(was.values())} → {sum(now.values())}, по файлам — как сейчас")
    for sec in (s for s in SECTIONS if s not in grown):
        for key, value in list(base.get(sec, {}).items()):
            was, now, now_n = number(value), state[sec].get(key), number(state[sec].get(key))
            if now is None:
                del base[sec][key]
                changed.append(f"{sec} «{key}»: убрано (было {was})")
            elif now_n < was:
                base[sec][key] = now
                changed.append(f"{sec} «{key}»: {was} → {now_n}")
    older = changes(model.root, stamp, model, "HEAD") if stamp and "repeats" in base else None
    for key in sorted(joined_repeats(seqs, dups, older, lim["repeat_lines"]) if older else ()):
        was, spots = base["repeats"].get(key, 0), dups[key]
        if len(spots) > was:
            base["repeats"][key] = len(spots)
            changed.append(f"repeats «{key}»: повтор из базы задет уборкой — {spots[0][0]}, мест "
                           + (f"{was} → " if was else "") + str(len(spots)))
    if changed:
        base["date"] = datetime.date.today().isoformat()
        save(base_path, base)
        print("\n".join(f"база: {line}" for line in changed))
    print(f"Итог: база {'снижена — изменений ' + str(len(changed)) if changed else 'без изменений'}; база {base['date']}.")
    return 0


def audit(model, base, lim, diff, rev, base_path):
    """Все находки и заметки одного прогона; diff — changes() с --changed, иначе None."""
    (hot, items), (stamp, rel) = hot_files(model.root, lim["hot_window"]), base_stamp(model.root, base_path)
    new = diff[0] if diff else None
    rep, moved = Report(new is not None, hot), renames(model, base, stamp, rev)
    check_sizes(model, base, lim, diff, rep, moved, (rev, stamp, "HEAD"))
    seqs, dups = windows(model, lim["repeat_lines"])
    since = diff or stamp and "repeats" in base and changes(model.root, stamp, model)  # без --changed — с коммита базы
    joined = joined_repeats(seqs, dups, since, lim["repeat_lines"]) if since else set()
    check_repeats(base, lim, diff, rep, seqs, dups, joined)
    check_helpers(base, new, rep, helpers(model, lim))
    found, names = counters(model)
    check_counters(model, base, diff, rep, found, names, moved)
    check_rules(model, rev, new, rep)
    check_raised(model, rev, rel, base, rep, lambda key: new is None or key in joined)  # без --changed — против HEAD
    note_classes(model, lim, new, rep)
    note_numbers(model, new, rep)
    note_dead(model, new, rep)
    note_design(model, new, rep)
    note_lines(model, lim, new, rep)
    for path, why in model.skipped.items() if new is not None else ():  # новый файл мимо замера — видно исполнителю
        if shown(model.root, rev, path) is None:
            rep.add(False, 0.5, path, None, f"мимо замера как сгенерированное: {why}", "рукописный — метку из шапки убрать")
    if new is None:
        note_project(model, lim, rep, found)
        for path, count in hot.items():
            if count >= lim["hot_edits"] and path in model.sources:
                rep.add(False, count / lim["hot_edits"], path, None,
                        f"горячий файл: задело пунктов {count} из {min(items, lim['hot_window'])} (заметка от "
                        f"{lim['hot_edits']})",
                        "раннер находит проверки сам: новая проверка — свой файл; перенести одну подсистему "
                        "(больше порога — несколькими файлами)" if is_check(path) and re.search(
                            r"run|harness|regist|suite", os.path.basename(path)) else
                        "разнести по частям — узкое место параллельных волн")
    return rep


def plural(n, one, few, many):
    n = abs(n) % 100
    return many if 11 <= n <= 19 else one if n % 10 == 1 else few if 2 <= n % 10 <= 4 else many


def queued_cleanups(root):
    text = "\n".join(read_lines(os.path.join(root, "docs", "ROADMAP.md")) or [])
    queue = re.search(r"(?ms)^## Очередь\s*$(.*?)(?=^## |\Z)", text)
    return len(re.findall(r"(?m)^\s*(?:[-*+]|\d+[.)])\s+.*\bУборка:", queue.group(1))) if queue else 0


def first_excess(root, rel, lim):
    """Строк сверх порога в базе, какой её записали (первая версия в git), как excess; None — не найти."""
    added = (git(root, "log", "--diff-filter=A", "--format=%H", "--", rel) or "").split() if rel else []
    first = as_base(shown(root, added[-1], rel)) if added else None
    files = first.get("files", {}) if first else {}
    return sum(max(0, number(v) - lim["file_lines"]) for v in files.values()) + sum(
        max(0, number(v) - lim["func_lines"]) for k, v in first.get("functions", {}).items()
        if k.split("::", 1)[0] not in files) if first else None


def summary(rep, root, rel, lim):
    """Одна строка словами продукта для /studio/board без имён файлов; места — находки и старое сверх порога.

    Строки сверх нормы — сверх порога у файлов и функций: их и снижают уборки, в том числе разнесением по файлам
    (мест может остаться столько же); при записи базы — только если с тех пор число другое.
    Прочие заметки (мёртвое, наборы чисел…) — материал /studio/retro; «код вырос сверх нормы» по коду 1 пишет /studio/board.
    """
    places = len(rep.findings) + rep.over
    if not places:
        return "в порядке"
    queued, grown = queued_cleanups(root), plural(places, "разрослось или повторяется", *["разрослись или повторяются"] * 2)
    was = first_excess(root, rel, lim) if rep.excess else None
    extra = f", строк сверх нормы {rep.excess}" + (f" (при записи базы {was})" if was not in (None, rep.excess) else "") \
        if rep.excess else ""
    return (f"{places} {plural(places, 'место', 'места', 'мест')} {grown}{extra} — {queued} "
            f"{plural(queued, 'уборка', 'уборки', 'уборок')} в очереди, игра от них не меняется")


def show(rep, head, date, only=None):
    """Находки, потом заметки — по 20; с --only — только строки с этим текстом, все (--only без текста — все строки)."""
    print(head)
    found, notes = ([x for x in items if only is None or only in x[1]] for items in (rep.findings, rep.notes))
    for title, items in (("Находки", found), ("Заметки", notes)):
        if items:
            print(f"{title} ({len(items)}):", *[text for _, text in sorted(items)[:None if only is not None else 20]],
                  sep="\n")
        if len(items) > 20 and only is None:
            print(f"… и ещё {len(items) - 20} — все: --only <файл или слово>, все строки — --only")
    print(f"Итог: находок {len(found)}, заметок {len(notes)}" + (f" со словами «{only}»" if only else "") + f"; база {date}")
    return 1 if found else 0


def print_limits(base):
    lim, own = limits_of(base)
    print("Пороги здоровья кода (свои — ключ limits в tools/code_baseline.json, менять — пунктом очереди с причиной):")
    for key, (default, why) in LIMITS.items():
        print(f"  {key} = {lim[key]} — {why}" + (f"; свой, по умолчанию {default}" if key in own else ""))
    print(f"Итог: порогов {len(LIMITS)}, своих {len(own)}.")
    return 0


def as_base(text):
    """База из текста JSON: словарь; не JSON или не словарь — None."""
    try:
        data = json.loads(text or "null")
    except ValueError:
        return None
    return data if isinstance(data, dict) else None


def load(path):
    """База: словарь; файла нет — None; не читается (конфликт слияния, обрыв записи) — False."""
    base = as_base("\n".join(read_lines(path) or [])) if os.path.exists(path) else None
    return False if base is None and os.path.exists(path) else base


def arguments():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--changed", nargs="?", const="HEAD", metavar="ХЕШ", help="только новое с коммита (HEAD)")
    for flag, text in (("--summary", "одна строка словами продукта для /studio/board"), ("--limits", "действующие пороги"),
                       ("--baseline", "записать базу (/studio/setup, /studio/setup обновить)"), ("--tighten", "снизить базу (/studio/done)"),
                       ("--add-new-metrics", "с --baseline: дописать только новые метрики")):
        parser.add_argument(flag, action="store_true", help=text)
    parser.add_argument("--only", nargs="?", const="", metavar="ТЕКСТ",
                        help="только строки с этим текстом (файл, имя), все, без обрезки; без текста — все строки")
    parser.add_argument("--root", help="папка проекта; по умолчанию текущая")
    parser.add_argument("--baseline-file", help=f"файл базы; по умолчанию {BASE} в папке проекта")
    args = parser.parse_args()
    modes = [args.summary, args.limits, args.baseline, args.tighten, args.changed is not None]
    if sum(modes) > 1 or args.add_new_metrics and not args.baseline or args.only is not None and sum(modes[:4]):
        parser.error("--changed, --summary, --limits, --baseline, --tighten — по одному; "
                     "--add-new-metrics — только с --baseline; --only — без флагов или с --changed")
    return args


def main():
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")
    args = arguments()
    root = os.path.abspath(args.root or os.getcwd())
    beside = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # <проект>/tools/code_check.py
    if not args.root and not os.path.isdir(os.path.join(root, "docs")) and any(  # проект в подпапке репозитория;
            os.path.exists(os.path.join(beside, mark)) for mark in (".git", BASE)):  # docs/ есть и у шаблонов плагина
        root = beside
    base_path = os.path.abspath(args.baseline_file or os.path.join(root, BASE))
    base = load(base_path)
    if args.limits:
        return print_limits(base)
    if base is False:  # --baseline её не заменяет: иначе храповик сбросился бы к нынешнему
        print("мерить нечем: база испорчена → /studio/setup обновить" if args.summary else
              f"База не читается: {base_path} — вернуть из git (git show HEAD:{BASE} > {BASE}), --baseline её не "
              "заменит.\nИтог: база испорчена — мерить не с чем.")
        return 2
    if (git(root, "rev-parse", "--is-inside-work-tree", check=True) or "").strip() != "true":
        print("мерить нечем → /studio/setup обновить" if args.summary else f"Итог: нет git в {root} — мерить нечем.")
        return 2
    rev = args.changed or "HEAD"
    if args.changed and git(root, "rev-parse", "--verify", "--quiet", rev + "^{tree}", check=True) is None:
        print(f"Итог: нет коммита {rev} — неверный вызов.")
        return 2
    if args.baseline and base is not None and not args.add_new_metrics:
        print(f"База уже есть: {base_path} — поднимать нельзя; снижает /studio/done (--tighten).\n"
              "Итог: база не записана — неверный вызов.")
        return 2
    # база — с принятого: как в HEAD, без чужих незакоммиченных правок; коммитов ещё нет — рабочая папка
    committed = (args.baseline or args.tighten) and git(root, "rev-parse", "--verify", "-q", "HEAD", check=True)
    model = Model(root, (base or {}).get("exclude", []), bool(committed), known_paths(base))
    if args.baseline:
        return write_base(model, base_path, base, args.add_new_metrics)
    if base is None:
        print("мерить нечем → /studio/setup обновить" if args.summary else f"Базы нет: {base_path} — записать: "
            "python -X utf8 tools/code_check.py --baseline (/studio/setup, /studio/setup обновить).\nИтог: базы нет — мерить не с чем.")
        return 2
    if args.tighten:
        return tighten(model, base_path, base)
    lim, _ = limits_of(base)
    rep = audit(model, base, lim, changes(root, rev, model) if args.changed else None, rev, base_path)
    if args.summary:
        print(summary(rep, root, base_stamp(root, base_path)[1], lim))
        return 1 if rep.findings else 0
    size = sum(s.size for _, s in model.code())
    title = (f"Код: файлов {len(model.sources)}, значимых строк {size}; база {base.get('date', '?')}"
             + (f"; только новое с {rev}" if args.changed else "")
             + (f"; чужие неотслеживаемые черновики (_scratch*) мимо: {model.foreign}" if model.foreign else "")
             + (f"; сгенерированное и сжатое мимо: {len(model.skipped)}" if model.skipped else "") + ".")
    return show(rep, title, base.get("date", "?"), args.only)


if __name__ == "__main__":
    sys.exit(main())
